from utility import *

# eg("the", "show options", oo)
# eg("rand", "demo random number generation", randFunc)
# eg("some", "demo of reservoir sampling", someFunc)
# eg("nums","demo of NUM", numFunc)
# eg("syms","demo SYMS", symFunc)
# eg("csv", "reading csv files", csvFunc)
# eg("data", "showing data sets", dataFunc)
# eg("clone","replicate structure of a DATA", cloneFunc)
# eg("cliffs", "stats tests", cliffsFunc)
# eg("dist","distance test", distFunc)
# eg("half","divide data in half", halfFunc)
# eg("tree","make snd show tree of clusters", treeFunc)
# eg("sway","optimizing", swayFunc)
# eg("bins","find deltas between best and rest", binsFunc)
# eg("xpln", "explore explanation sets", explnFunc)
