name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Running test cases with pytest
    #   run: python -m pytest 
    - name: Running custom test engine to output
      run: python ./src/main.py
    
    
    - name: Generate Report
      run: |
        pip install coverage
        coverage run ./src/main.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 74ecbcfc-3a85-4a4e-bc26-a496347b91c9
